INSERT INTO RECIPIENT_ENTITY (id, RECIPIENT_ID, EMAIL, PHONE_NUMBER, PUSH_TOKEN)
VALUES (1, 'recipient_1', 'abc@example.com', '123456789', 'token_123');

INSERT INTO RECIPIENT_ENTITY (id, RECIPIENT_ID, EMAIL, PHONE_NUMBER, PUSH_TOKEN)
VALUES (2, 'recipient_2', 'def@example.com', '987654321', 'token_456');

INSERT INTO RECIPIENT_ENTITY (id, RECIPIENT_ID, EMAIL, PHONE_NUMBER, PUSH_TOKEN)
VALUES (3, 'recipient_3', 'ghi@example.com', '456123789', 'token_789');